
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Harsh
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
     String firstName;
    String firstEmail;
    String firstCardno;
    String firstPin;
    int balance;
    
    public FastCash() {
        initComponents();
    }

    public FastCash(String firstName, String firstEmail, String firstCardno, String firstPin, int balance) {
        this.firstName = firstName;
        this.firstEmail = firstEmail;
        this.firstCardno = firstCardno;
        this.firstPin = firstPin;
        this.balance = balance;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn10000 = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn1000 = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        btn4000 = new javax.swing.JButton();
        btn6000 = new javax.swing.JButton();
        btn8000 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn10000.setBackground(new java.awt.Color(0, 102, 102));
        btn10000.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn10000.setForeground(new java.awt.Color(255, 255, 255));
        btn10000.setText("Rs 10000");
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(0, 102, 102));
        btncancel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BANDHAN BANK ATM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("FAST CASH");

        btn1000.setBackground(new java.awt.Color(0, 102, 102));
        btn1000.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn1000.setForeground(new java.awt.Color(255, 255, 255));
        btn1000.setText("Rs 1000");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn2000.setBackground(new java.awt.Color(0, 102, 102));
        btn2000.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn2000.setForeground(new java.awt.Color(255, 255, 255));
        btn2000.setText("Rs 2000");
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });

        btn4000.setBackground(new java.awt.Color(0, 102, 102));
        btn4000.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn4000.setForeground(new java.awt.Color(255, 255, 255));
        btn4000.setText("Rs 4000");
        btn4000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4000ActionPerformed(evt);
            }
        });

        btn6000.setBackground(new java.awt.Color(0, 102, 102));
        btn6000.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn6000.setForeground(new java.awt.Color(255, 255, 255));
        btn6000.setText("Rs 6000");
        btn6000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6000ActionPerformed(evt);
            }
        });

        btn8000.setBackground(new java.awt.Color(0, 102, 102));
        btn8000.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        btn8000.setForeground(new java.awt.Color(255, 255, 255));
        btn8000.setText("Rs 8000");
        btn8000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8000ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4000)
                    .addComponent(btn1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn2000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn10000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn8000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btncancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1000)
                    .addComponent(btn6000))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn8000)
                    .addComponent(btn2000))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4000)
                    .addComponent(btn10000))
                .addGap(18, 18, 18)
                .addComponent(btncancel)
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
       /* int balance = this.balance;
        if (balance > 1000) {
            balance = balance - 1000;
            String message = "You have successfully withdrawed " + 1000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }*/
    }//GEN-LAST:event_btn10000ActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
         First first = new First(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, this.balance);
        first.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        int balance = this.balance;
        if (balance > 1000) {
            balance = balance - 1000;
            String message = "You have successfully withdrawed " + 1000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
       int balance = this.balance;
        if (balance > 2000) {
            balance = balance - 2000;
            String message = "You have successfully withdrawed " + 2000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btn4000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4000ActionPerformed
        int balance = this.balance;
        if (balance > 4000) {
            balance = balance - 4000;
            String message = "You have successfully withdrawed " + 4000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn4000ActionPerformed

    private void btn6000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6000ActionPerformed
       int balance = this.balance;
        if (balance > 6000) {
            balance = balance - 6000;
            String message = "You have successfully withdrawed " + 6000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn6000ActionPerformed

    private void btn8000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8000ActionPerformed
       int balance = this.balance;
        if (balance > 8000) {
            balance = balance - 8000;
            String message = "You have successfully withdrawed " + 8000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn8000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn10000;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn4000;
    private javax.swing.JButton btn6000;
    private javax.swing.JButton btn8000;
    private javax.swing.JButton btncancel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
